
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/spring_demo?useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
  jackson:
    default-property-inclusion: non_null
    date-format:  yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  freemarker:
    allow-request-override: false
    allow-session-override: false
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    enabled: true
    suffix: .ftl
    request-context-attribute: ctx

  redis:
    host: 127.0.0.1
    port: 6379

#  resources:
#    static-locations: classpath:/static/

#  thymeleaf:
#    cache: false
#    mode: html


logging:
  level:
    root: warn
    com.gxdemo.dao: trace
  pattern:
    console: '%p%m%n'

mybatis-plus:
  mapper-locations: classpath*:/mappers/*.xml
  type-aliases-package: com.gxdemo.dto


#server:
#  servlet:
#    context-path: /sell


webSet:
  rootUrl: 127.0.0.1:8080${server.servlet.context-path:}

wechat:
  mpAppid: wx618302afd7e9bf6b
  mpAppSecret: e26db230bcf467cff504a582f6ee7de9
  mcAppAppid: wx07cefac8f6ba6e89
  mchId: 1481117802
  mchKey: 3f9e3790504290606c590803247dfa53
  keyPath: classpath:/cert/apiclient_cert.pem
  notifyUrl: http://${webSet.rootUrl}/pay/notify
  authUrl: http://${webSet.rootUrl}/wechat/userInfo




