export const SET_SINGER = 'SET_SINGER'
export const SET_ALBUM = 'SET_ALBUM'
export const SET_PLAYING_STATE = 'SET_PLAYING_STATE'
export const SET_FULLSCREEN = 'SET_FULLSCREEN'
export const SET_PLAYLIST = 'SET_PLAYLIST'
export const SET_SEQUENCE_LIST = 'SET_SEQUENCE_LIST'
export const SET_PLAY_MODE = 'SET_PLAY_MODE'
export const SET_CURRENT_INDEX = 'SET_CURRENT_INDEX'

export const INS_PLAYLIST = 'INS_PLAYLIST'
export const INS_SEQUENCE_LIST = 'INS_SEQUENCE_LIST'

export const SPLICE_PLAYLIST = 'SPLICE_PLAYLIST'
export const SPLICE_SEQUENCE_LIST = 'SPLICE_SEQUENCE_LIST'

export const SET_SEARCH_HISTORY = 'SET_SEARCH_HISTORY'
export const SET_PLAY_HISTORY = 'SET_PLAY_HISTORY'
export const SET_FAVORITE_LIST = 'SET_FAVORITE_LIST'